### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by simkim** [simkim/dlcenter#17]

**Comment by simkim** [comment]
Without margin, but it's ugly

![Capture d’écran du 2020-05-02 15-45-08](https://user-images.githubusercontent.com/1174971/80865814-f8c19380-8c8b-11ea-93b6-0a62fe5c8221.png)

**Comment by simkim** [comment]
@aquainon do you have an idea about mobile UX ?

**Comment by genezys** [comment]
I wonder if shared files should be first, before the actions to add...

**Comment by aquainon** [comment]
I would suggest to take the wetransfer approach with a step-by-step experience:
![image](https://user-images.githubusercontent.com/20782906/80866170-9c5f7380-8c8d-11ea-804c-33f61d890d4f.png)
![image](https://user-images.githubusercontent.com/20782906/80866174-9f5a6400-8c8d-11ea-97f6-e32c7f3a35b6.png)
![image](https://user-images.githubusercontent.com/20782906/80866178-a2555480-8c8d-11ea-84ba-3525eb225e9e.png)
![image](https://user-images.githubusercontent.com/20782906/80866180-a41f1800-8c8d-11ea-8fed-d01d6e0faa1f.png)

**Comment by genezys** [comment]
I tried in the responsive editor of Safari and WeTransfer appears to trigger a completely different UI when it detects some very specific sizes of screen. Of course they missed a few so it does not trigger in the iPad sidebar or split-view. I am not sure this is the best approach given the limited resources of dlcenter...

**Comment by genezys** [comment]
Here is a test on iPhone & iPad removing the top margin & trying the shared files on top.

# iPhone 8

<img width="50%" alt="Capture d’écran 2020-05-02 at 16 08 37" src="https://user-images.githubusercontent.com/65271/80866487-455a9e00-8c8f-11ea-92b8-09c6633f12bd.png"><img width="50%" alt="Capture d’écran 2020-05-02 at 16 08 21" src="https://user-images.githubusercontent.com/65271/80866493-47bcf800-8c8f-11ea-83a0-0f28496a3f5b.png">

# iPad Pro
![Capture d’écran 2020-05-02 at 16 09 55](https://user-images.githubusercontent.com/65271/80866612-f103ee00-8c8f-11ea-9ec8-d7cbb5260d8b.png)

**Comment by aquainon** [comment]
@genezys I think also that added files should appear first, important for the use case where you want to download the files

**Comment by aquainon** [comment]
I really like the mobile view. I also love the background picture, but for mobile layout I think you should drop it, the margins are too small and we can't see anything of the picture.

**Comment by aquainon** [comment]
And the desktop layout would really breath with more margins, maybe the non-features items (credits, logo and so on) could be kept outside of the block

**Comment by simkim** [comment]
![Capture d’écran du 2020-05-02 16-31-15](https://user-images.githubusercontent.com/1174971/80867051-6244a080-8c92-11ea-987e-7fd841d379a9.png)

```
@media screen and (max-width: 700px) {
  html {
    background: white;
  }
  .dropzone {
    border: 0;
  }
  .main-view {
    border: 0;
    border-radius: 0;
    box-shadow: none;
    margin: 0;
  }
  .share {
    flex-direction: column;
  }
  .position-switch {
    display: flex;
    flex-direction: column-reverse;
  }
}
```

**Comment by genezys** [comment]
I agree with the full width & no background for smaller screen, it seems clearer.

But 700px feels a bit large, an iPad in split screen is 500px wide and I think it does not deserve a too degraded UI.

I am also wondering about the flex direction column for shares. Maybe it should be reserved for really small screens.

**Comment by genezys** [comment]
I added the layout change at 500px instead of 700px.

To me, this looks good enough.

# iPad Full
![iPad Full](https://user-images.githubusercontent.com/65271/80867329-f82cfb00-8c93-11ea-99c5-7153526c2ba8.png)

# iPad Split-view
![iPad Split](https://user-images.githubusercontent.com/65271/80867332-fd8a4580-8c93-11ea-9931-83dbc3ec9c24.png)

# iPad in sidebar
![iPad Side](https://user-images.githubusercontent.com/65271/80867345-07ac4400-8c94-11ea-82d8-88f9207eb7a7.png)

**Comment by aquainon** [comment]
This looks great! Here are my thoughts:
![image](https://user-images.githubusercontent.com/20782906/80867630-7938c200-8c95-11ea-8cfa-8cfbe891a69f.png)

**Comment by genezys** [comment]
I agree that moving some content outside the box would be great but I don't know how to layout them on top of the random background.

**Comment by simkim** [comment]
@genezys I let you push your changes. 

I setup a first workflow on heroku

**Comment by simkim** [comment]
> I agree that moving some content outside the box would be great but I don't know how to layout them on top of the random background.

It's not a blocker we can deploy without this and improve later

**Comment by genezys** [comment]
I added margin and centered the Download All. I am not sure about the Download All, I like that it was below the others.

![Capture d’écran 2020-05-02 at 17 01 29](https://user-images.githubusercontent.com/65271/80867849-b782b100-8c96-11ea-816c-d23e7d322e45.png)

**Comment by simkim** [comment]
ok !
