### ISSUE TITLE
https://dl.center ne répond pas

### ISSUE THREAD

**Issue by genezys** [simkim/dlcenter#22]
Chez moi, impossible d'ouvrir dl.center

**Comment by simkim** [comment]
Il se bloque régulièrement, je dois redémarrer le docker

**Comment by genezys** [comment]
Un petit service d’auto restart toutes les nuits ?

**Comment by genezys** [comment]
![Uploading Capture d’écran 2020-09-22 à 00.08.47.png…]()

**Comment by simkim** [comment]
Oui, je vais voir

**Comment by simkim** [comment]
j'ai ajouté un redemarrage à 5h

**Comment by genezys** [comment]
De nouveau indisponible
